name: rename_lanhu
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_chooser:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      ref: master
      path: plugins/file_chooser
  file_selector_platform_interface:
    git:
      url: https://github.com/flutter/plugins.git
      ref: master
      path: packages/file_selector/file_selector_platform_interface
  create_material_color: ^0.0.2
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  file_picker: ^2.0.11
  flushbar: ^1.10.4
  flutter_bloc: ^6.0.6
  freezed_annotation: ^0.12.0
  get_it: ^5.0.1
  injectable: ^1.0.5
  ionicons: ^0.0.3
  modal_progress_hud: ^0.1.3
  path_provider: ^1.6.21
  progress_dialog: ^1.2.4
  provider: ^4.3.2+2
  rxdart: ^0.24.1
  shared_preferences: ^0.5.12+2
  stringx: ^0.0.5+1
  time: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  freezed: ^0.12.2
  injectable_generator: ^1.0.6
  scrollable_positioned_list: ^0.1.8

flutter:

  uses-material-design: true
  
dependency_overrides:
  meta: 1.2.3
  analyzer: 0.40.5
  build_runner: 1.10.0

scripts: derry.yaml
